### ISSUE TITLE
Do not build the iterator each time

### ISSUE THREAD

**Issue by Arcesilas** [nette/finder#10]
Hi again,

I've noticed that the iterator is created each time we iterate on the Finder (or I missed something in the way iterators work, which is really possible).

The `getIterator` method always call `buildIterator` which creates a new instance.

Could it be possible to not always create it and keep it cached to be re-used?

I understand that from between two iterations, the filesystem may have changed. But in some cases, we know it does not.

Use case example: I want to build a static website. I iterate over the files one first time, to gather data (categories, tags, authors, etc.). Then I iterate a second time to compile all files, using the data collected during the first pass. If the filesystem has changed, it's my responsibility. When I build the static website, I build it, I don't write its content.

This could be a new method (`findFilesOnce` for example) which would set an option to keep the iterator cached for latter use.

EDIT: I may provide a PR to add this feature.

**Comment by JanTvrdik** [comment]
Have you considered simply using `iterator_to_array` to cache the result?

**Comment by Arcesilas** [comment]
Ahem... no... but I should.
Thanks.

**Comment by Arcesilas** [comment]
But... actually, if I use `iterator_to_array`, the data will be iterated 3 times... Which is worse than not "caching" the data with that function.

**Comment by JanTvrdik** [comment]
> the data will be iterated 3 times

I don't understand. Can you elaborate?

**Comment by Arcesilas** [comment]
First, when executing `iterator_to_array`, php iterate over the iterator to build the array. Then, I iterate over the array for the first pass, and one third time for the second pass. 3 iterations.
If I don't "cache" the data with `iterator_to_array`, I iterate only twice over the data. But the iterator is also built twice.
Caching the iterator allows to build it once and to iterate twice only.

**Comment by JanTvrdik** [comment]
I don't see why that's a problem. 3 faster iterations are no worse than 2 slower iterations.
