### ISSUE TITLE
PHP 7.4 - Cannot use "parent" when current class scope has no parent

### ISSUE THREAD

**Issue by mabar** [nette/finder#11]
PHP 7.4 reports `E_DEPRECATED: Cannot use "parent" when current class scope has no parent` at [this line](https://github.com/nette/finder/blob/13240336bd80f9260cd35a3894b8c1aab9586ec2/src/Utils/Finder.php#L372). I am not sure what is purpose of parent call here, but shouldn't it be `$this->`?

https://travis-ci.org/contributte/di/jobs/554846041#L242-L262

**Comment by ondrejmirtes** [comment]
I'd like this fix to be released, thank you.

**Comment by dg** [comment]
Done

**Comment by ondrejmirtes** [comment]
Thank you!
