### ISSUE TITLE
Maximum execution time of 90 seconds exceeded

### ISSUE THREAD

**Issue by roher-roher** [nette/finder#12]
Version: 2.5.2

### Bug Description
Hi, I am using Nette framework.
I get the following exception several times an hour when users are browsing my website (on different pages):
Fatal Error: Maximum execution time of 90 seconds exceeded in <my path to webroot>/vendor/nette/finder/src/Utils/Finder.php:234

I have slightly modified the Finder.php to add some additional logging:
```php
	private function buildIterator(string $path): \Iterator
	{
		$iterator = new RecursiveDirectoryIterator($path, RecursiveDirectoryIterator::FOLLOW_SYMLINKS);

		if ($this->exclude) {
			$iterator = new \RecursiveCallbackFilterIterator($iterator, function ($foo, $bar, RecursiveDirectoryIterator $file): bool {
				if (!$file->isDot() && !$file->isFile()) {
					foreach ($this->exclude as $filter) {
						if (!$filter($file)) {
							return false;
						}
					}
				}
				return true;
			});
		}

		if ($this->maxDepth !== 0) {
			$iterator = new RecursiveIteratorIterator($iterator, $this->order);
			$iterator->setMaxDepth($this->maxDepth);
		}

		Debugger::enable(Debugger::DETECT, __DIR__ . '/../../../../../log', 'admins@droidoncar.com');

		Debugger::log("path: " . $path, Debugger::INFO);

		$iterator = new \CallbackFilterIterator($iterator, function ($foo, $bar, \Iterator $file): bool {

			Debugger::log("file: " . get_class($file) . " at iteration 0", Debugger::INFO);
			$i = 0;

			while ($file instanceof \OuterIterator) {
				$file = $file->getInnerIterator();
				Debugger::log("file: " . get_class($file) . " at iteration " . ++$i, Debugger::INFO);
			}

			foreach ($this->groups as $filters) {
				foreach ($filters as $filter) {
					if (!$filter($file)) {
						continue 2;
					}
				}
				return true;
			}
			return false;
		});

		return $iterator;
	}
```

Here is the output:

> [2020-12-26 00-06-08] path: <my path to webroot>/app/../temp/cache  @  https://@@@.com/main/forums?backUrl=fld1n
[2020-12-26 00-06-08] file: RecursiveIteratorIterator at iteration 0  @  https://@@@.com/main/forums?backUrl=fld1n
[2020-12-26 00-06-08] file: RecursiveDirectoryIterator at iteration 1  @  https://@@@.com/main/forums?backUrl=fld1n
[2020-12-26 00-06-08] file: RecursiveIteratorIterator at iteration 0  @  https://@@@.com/main/forums?backUrl=fld1n
[2020-12-26 00-06-08] file: RecursiveDirectoryIterator at iteration 1  @  https://@@@.com/main/forums?backUrl=fld1n
[2020-12-26 00-06-08] file: RecursiveIteratorIterator at iteration 0  @  https://@@@.com/main/forums?backUrl=fld1n
[2020-12-26 00-06-08] file: RecursiveDirectoryIterator at iteration 1  @  https://@@@.com/main/forums?backUrl=fld1n
... Endless cycle until maximum execution time exceeded ...

### Steps To Reproduce
I don't know the steps as I can't reproduce the problem myself, I only get notifications about the exception.

### Expected Behavior
No error is expected.

**Comment by dg** [comment]
Can you try to log files instead of class names, ie. `"file: " . $file . "`

**Comment by roher-roher** [comment]
Hi dg, I have tried before switching to class names, but it throws an error:
>> Recoverable Error: Object of class RecursiveIteratorIterator could not be converted to string

**Comment by dg** [comment]
I mean the log after `$file = $file->getInnerIterator()`.

**Comment by roher-roher** [comment]
Thank you, I've enabled the logging after getInnerIterator, and it turned out that it was iterating through my website php sessions directory which had 1.5+ billion files. Looks like I've forgotten to setup cron job that clears old session files when reinstalling the server. And (what a surprise!) it really takes more 90 seconds to iterate though them.

Hence, there is no issue in Finder.
