### ISSUE TITLE
Readme instructions don't install project

### ISSUE THREAD

**Issue by paulhennell** [nette/finder#15]
Just had a silly few mins trying to use this project and php complaining it couldn't find Finder class. Couldn't understand the code to see Finder either, so came here and got very confused why it was all different.

Eventually realised that the readme says `composer require nette/utils` where as you actually need `composer require nette/finder` to get this project.

Figured it was a typo I could PR, but then saw you've a single commit changing `finder` to `utils` in the instructions which looks more intentional: https://github.com/nette/finder/commit/c93ddaf7fc32cf4c0d312fa47ea47f2fa89da1ce

Was this change intentional? Is there a way installing with /utils should work?

**Comment by dg** [comment]
That's a mistake, there really should be a nette/finder.
