### ISSUE TITLE
Throw exception if you haven't last call methods from() or in()

### ISSUE THREAD

**Issue by h4kuna** [nette/finder#7]
# Motivation
Two times happen me, i forgot for this behavior, when you must call from() or in() like a last methods.

# Describe problem
This is right and works fine. This example is in documentation.
```php
Finder::findFiles('*.php')->date('>', '- 2 weeks')->from($dir);
```
But if you change call of methods, because both are support fluent.
```php
Finder::findFiles('*.php')->from($dir)->date('>', '- 2 weeks');
```
The example could throw exception.

This is bad, because on first look, it is ok, nothing happend.
But it works bad. Every time i seach why does not work, because it rewrites internal reference.

# Resolve problem
One instance of Finder is for one search. I think internal state can freeze after call in() or from() and throw exception if you call other methods exclude interface's methods.

**Comment by h4kuna** [comment]
I can prepare PR.

**Comment by dg** [comment]
That's probably not possible without breaking the backward compatibility. However for version 3 I'm going to make a whole new API.

**Comment by h4kuna** [comment]
Ok
