### ISSUE TITLE
Symbols in description item of composer.json cause issue in Gitlab

### ISSUE THREAD

**Issue by ockstadt** [nette/finder#8]
Dear developers,
we have an issue when integrating your nette/* packages. Our current version of Gitlab (GitLab Enterprise Edition 11.2.5-ee) and the MariaDB behind it seem to be unable to handle your symbols in the description items of your composer.json files. Thus we can not create merge requests anymore.

> "description": "🔍 Nette Finder: find files and directories with an intuitive API.",

Do you think it is possible that you remove these symbols and provide new patch versions of all of your packages?

To be precise, we have these dependencies
- 🅱 Nette Bootstrap
- 💎 Nette Dependency Injection Container
- 🔍 Nette Finder
- 🍸 Nette NEON
- 🐘 Nette PHP Generator
- 🍀 Nette RobotLoader
- 📐 Nette Schema
- 🛠 Nette Utils

Thank you in advance!

Regards

**Comment by mabar** [comment]
Imho you should change charset to utf8mb4

**Comment by JanTvrdik** [comment]
This needs to fixed on gitlab side.

**Comment by ockstadt** [comment]
Thank you!
We have maintenance windows and cannot fix this before mid of May. I thought a larger number of users could have noticed this issue and you might change it in your packages.
Regards
